/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("StudentObjectPageObjectPage journey");

        opaTest("Navigate to StudentObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheStudentList.onFilterBar().iExecuteSearch();

            Then.onTheStudentList.onTable().iCheckRows();
            When.onTheStudentList.onTable().iPressRow(0);

            Then.onTheStudentObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheStudentObjectPage.iCheckNumberOfSections(2);
            When.onTheStudentObjectPage.iPressSectionIconTabFilterButton("StudentDetails");
            Then.onTheStudentObjectPage.iCheckSection({ section: "StudentDetails" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "StudentNumber" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "FirstName" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "LastName" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "Email" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "CreatedBy" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "StudentYear" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "CreatedAt" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "LastChangedAt" });
            Then.onTheStudentObjectPage.onForm({ section: "StudentDetails" }).iCheckField({ property: "LocalLastChangedAt" });
            When.onTheStudentObjectPage.iPressSectionIconTabFilterButton("Enrollments");
            Then.onTheStudentObjectPage.iCheckSection({ section: "Enrollments" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});